# Generated by Django 2.2.3 on 2019-07-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mobile_phone',
        ),
    ]
