# Generated by Django 2.2.3 on 2019-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_member_mobile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
